codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...50"

  status:
    project: yes
    patch: yes
      default:
        target: 0%
        threshold: 0%
        base: auto
        only_pulls: true
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
