name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list current folder
      run: ls -l
    - name: install libxml2
      run: sudo apt-get -y install libxml2-dev
    - name: install python-libxml2
      run: sudo apt-get -y install python-libxml2
    - name: make
      run: make

