name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UnitTests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list current folder
      run: ls -l
    - name: install libxml2
      run: sudo apt-get -y install libxml2 libxml2-dev
    - name: install python-libxml2
      run: sudo apt-get -y install python-libxml2 python2-devel python3-devel 
    - name: use gun89
      run: export CFLAGS="${CFLAGS-} -std=gnu89"
    - name: setup make
      run: make install
    - name: make
      run: make all
    - name: Do unit tests
      run: make unit

